### ISSUE TITLE
nieuw ontwerp intro-headers bouwen

### ISSUE THREAD

**Issue by wingsvn** [fdnd-agency/biebinbloei.nl#466]
`intro-headers.svelte` is een component dat wordt gebruikt binnen de agenda/workshop pagina. Dit component komt op meerdere pagina's terug. 

Dit component moet worden herbouwd volgens het nieuwe ontwerp. Het component bestaat momenteel alleen uit een beschrijving. Voor het nieuwe ontwerp moet er een titel aan worden toegevoegd.

**Comment by wingsvn** [comment]
# data in Hygraph
In Hygraph heb ik in het contentmodel `heroHeader` het veld `title` toegevoegd.

Het contentmodel `heroHeader` in Hygraph bestaat uit de velden: `heading1`, `description` en `heroImage`.
Hier heb ik een veld `title` aan toegevoegd.

# data in GraphQL
Om `title` op te halen uit Hygraph, voeg ik dit veld toe aan de graphQL query in `agenda/+page.server.js`

# weergeven van data in component 

In `agenda/+page.svelte` wordt  data uit`heroHeaders` door gegeven aan het component `IntroHeaders` via de prop `heroInfo`.

```svelte
<IntroHeaders heroInfo={data.heroHeaders[3]} />
```

In `intro-headers.svelte` wordt deze prop ontvangen en gebruik ik deze om data weer te geven.

``` svelte
<script>
	let { heroInfo } = $props();
</script>

<h2>{heroInfo.title}</h2>
```

# styling: intro-headers component

Ik heb flexbox gebruikt om de elementen onder elkaar te in te delen.

```css
section {
		display: flex;
		flex-direction: column;
}
```

Ik heb volgens het principe `mobile-first` gewerkt.
Met `@media` voeg ik extra ruimte (spacing) toe voor bredere schermen zoals tablets en desktops. Voor een betere leesbaarheid en toegankelijkheid heb ik een `max-width` toegepast op de tekst, zodat deze niet te breed wordt op grotere schermen.

```css
@media (min-width: 74rem) {
		section {
			margin: 5.5em 0 3.5em 0;
			gap: 1.5em;
			padding: 1.5em;
		}

		h2 {
			margin-top: -1.25em;
		}

		p {
			max-width: 500px;
		}
	}
```

# styling van de title

Om de titel over 2 regels op te splitsen, heb ik de string in 2 delen gesplits... met `split(' ')` en `<br>`

```svelte
        <h2>
		{heroInfo.title.split(' ')[0]}<br />
		{heroInfo.title.split(' ')[1]}
	</h2>
```

Om het eerste woord van de `title` anders te stylen gebruik ik een `<span>` met de class `outline`.

```svelte
        <h2>
		<span class="outline">{heroInfo.title.split(' ')[0]}</span><br />
		{heroInfo.title.split(' ')[1]}
        </h2>
```

```css
       .outline {
		color: transparent;
		-webkit-text-stroke: 1.5px var(--main-color-green);
	}
```


![Image](https://github.com/user-attachments/assets/32f976c9-3ed6-4881-9f40-d29bd94bcc0a)
