### ISSUE TITLE
[FEATURE]: consistentie buttons over alle pagina's

### ISSUE THREAD

**Issue by wingsvn** [fdnd-agency/biebinbloei.nl#500]
Er zijn meerdere componenten voor in principe dezelfde button styles. Om de code droger te maken en het hergebruiken van componenten te optimaliseren, probeer ik zoveel mogelijk gebruik te maken van dezelfde button component.

**Comment by wingsvn** [comment]
### agendabuttons voor de agenda carrousel op de homepage:
In het component `agendacarrousel` heb ik het `agendabutton` component vervangen door de `button` component. Daarbij heb ik kleine aanpassingen gemaakt in de marges van de workshop kaartjes, aangezien de nieuwe buttons meer ruimte innemen.
De `Agendabutton` component kan nu verwijderd worden.

### button voor de contactform op de contact pagina
Het `button` component is gebaseerd op een `a` element. Omdat de `button` in het `contactform` een `button type=submit` is, heb ik hier niet het `button` component geïmporteerd. In plaats daarvan heb ik de stijl van de button in de css van de desbetreffende `contactform` file aangepast naar de nieuwe stijl.

### button op de geveltuin 
Ik heb de oorspronkelijke `GeveltuinButton` vervangen door de `Button` component. In eerste instantie kwam de button buiten de normale flow te staan, omdat er een `position: absolute` op de `Button` component staat voor het positioneren van de buttons. Dit zorgde ervoor dat de button op de geveltuinpagina “random” ergens zweefde.

```css
.button-wrapper {
		display: flex;
		flex-direction: column;
		align-items: center;
                 position: absolute;
		right: 1em;
		bottom: 1em;
	}
```


 Om dit op te lossen heb ik een nieuwe prop `layout` toegevoegd aan de `Button` component. Deze prop bepaalt straks de positionering van de button door een corresponderende CSS-klasse toe te voegen aan de button-wrapper:

```js
<script>
	let {
		href,
		buttonText,
		buttonClass,
		svgFill,
		layout = "absolute"
	} = $props();
</script>
```
```svelte
<div class="button-wrapper {layout}">
```

`layout="absolute"` = **default button layout**
Binnen het Button component krijgt de button standaard de `position: absolute` mee via de class `absolute` op de wrapper-div. Dit zorgt ervoor dat de button altijd op een vaste positie op de pagina staat.

```css
.button-wrapper.absolute {
		position: absolute;
		right: 1em;
		bottom: 1em;
	}
```

`layout="inline"` 
Op de geveltuinpagina geef ik `layout="inline"` mee aan de `Button`, zodat de button niet de `.absolute` class krijgt. De button gebruikt dan alleen de basisstyling van `.button-wrapper` en vloeit mee in de inline/normale flow.

```css
.button-wrapper {
		display: flex;
		flex-direction: column;
		align-items: center;
	}
```
